### ISSUE TITLE
Sidebar - Study in Australia / China: ul content was aligned to center. It should be left aligned

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Modern-Education-Student-Exchange-Services#127]
![image](https://cloud.githubusercontent.com/assets/12888048/10330976/26fc0e26-6d04-11e5-905c-e951aa36a531.png)
![image](https://cloud.githubusercontent.com/assets/12888048/10330979/2ad8570c-6d04-11e5-94e0-370322037ea1.png)
![image](https://cloud.githubusercontent.com/assets/12888048/10330983/3059d764-6d04-11e5-80de-f517cd93d63e.png)

**Comment by Santosh-titan** [comment]
This issue is already fixed.

**Comment by romatitan** [comment]
Kindly check again on S4 and iPodtouch5 landscape view.
