### ISSUE TITLE
Clarification: Which one is the correct visa hover image? Upload one visa image only for its hover to avoid confusion of which is the correct one to use.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Modern-Education-Student-Exchange-Services#141]
![image](https://cloud.githubusercontent.com/assets/12888048/10424264/5322ad8e-7100-11e5-9a6a-bb006dd03705.png)

**Comment by Santosh-titan** [comment]
Please use visa-hover.png as leadin hover image

**Comment by romatitan** [comment]
Kindly remove/delete the other unnecessary visa hover images.
