### ISSUE TITLE
All pages & posts: Chinese characters did not display in front-end

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Modern-Education-Student-Exchange-Services#165]
NOTE: All PAGES and POSTS (Chinese translated page)
Homepage
Study in Australia
Study in Australia single page
Study in China
Study in China single page
About Us 
FAQ
English Book Club
News
News single page
Contact Us
Sitemap
Gallery
Thank you
Error page

e.g Page
![image](https://cloud.githubusercontent.com/assets/12888048/10656824/bfae3740-78b5-11e5-84e1-6fc0cd49443d.png)

e.g Post
![image](https://cloud.githubusercontent.com/assets/12888048/10656815/a1fe179c-78b5-11e5-8f88-8dd24651e94d.png)

**Comment by Santosh-titan** [comment]
Issues Fixed
