### ISSUE TITLE
Clarification - Sidebar Australia&China: Is there a restriction of how many post titles or all are needed to be displayed in the sidebar?

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Modern-Education-Student-Exchange-Services#35]
If there's a restriction of how many post title to be displayed, can a user/client choose which item(s) they wanted to be featured?

![image](https://cloud.githubusercontent.com/assets/12888048/9622737/cbcd0916-5169-11e5-8c56-d45bdcae517e.png)
![image](https://cloud.githubusercontent.com/assets/12888048/9622738/cd9fcba2-5169-11e5-988d-ea42bc4ce55a.png)

![image](https://cloud.githubusercontent.com/assets/12888048/9622764/38e8ec4a-516a-11e5-9b8e-208956acc354.png)

**Comment by Santosh-titan** [comment]
Post count was not mentioned in scope document. As displaying recent 4 posts as like in design.

**Comment by romatitan** [comment]
I created a new post in order to check this.
But, it did not display the recent post in the sidebar like what you said.
Kindly check again.

Note: I'll label this as a bug, as it should be properly implemented

**Comment by romatitan** [comment]
As what you have said, post count was not mentioned in the project, with that you will follow the design and display the 4 recent posts. 
However, the last time I check the sidebar, it did not display the recent [added] post. 
And now, you display all the posts in the sidebar.

Kindly check this screenshot for your reference.
![image](https://cloud.githubusercontent.com/assets/12888048/10212147/a724c95c-682d-11e5-8104-fd023d1d79b0.png)

**Comment by Santosh-titan** [comment]
as you asked recent 4 posts are now showing.
