### ISSUE TITLE
Homepage: Page title in red color was static and can't be edited.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Modern-Education-Student-Exchange-Services#4]
![image](https://cloud.githubusercontent.com/assets/12888048/9595111/3da44672-5097-11e5-8e7e-25879d91ef8f.png)

**Comment by Santosh-titan** [comment]
Its is a site tagline. You can edit it from here http://meses.stage.titanweb.com.au/wp-admin/options-general.php

**Comment by romatitan** [comment]
It should be part of the H1 as well.
Try to you the HTML <span> Tag for this.
