### ISSUE TITLE
Header: Button for language translation has no function.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Modern-Education-Student-Exchange-Services#49]
![image](https://cloud.githubusercontent.com/assets/12888048/9623549/fd509ad8-5174-11e5-882a-7c01a64693cf.png)

**Comment by Santosh-titan** [comment]
We sent a mail to jolean regarding translation functionality. I'm waiting for her response.

**Comment by Santosh-titan** [comment]
Functionality implemented. But need to add chinese content as of now i don't have chinese content.
