### ISSUE TITLE
Study in China: "Translate into chinese" label/button has no function

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Modern-Education-Student-Exchange-Services#50]
![image](https://cloud.githubusercontent.com/assets/12888048/9623558/22820e04-5175-11e5-8204-6f3d7557dd9b.png)

**Comment by Santosh-titan** [comment]
We sent a mail to jolean regarding translation functionality. I'm waiting for her response.

**Comment by Santosh-titan** [comment]
Language switcher implemented
