### ISSUE TITLE
Clarification - Visa Leads: Should the visa lead-ins have a hover state? The design was not clear.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Modern-Education-Student-Exchange-Services#6]
![image](https://cloud.githubusercontent.com/assets/12888048/9595453/3da9be0c-5099-11e5-86b1-18b3e45b1984.png)

**Comment by romatitan** [comment]
As per the design, it should have an alternate color of #d71921 and #c10013 per item as its active/hover state.
Kindly refer to the given design and/or clarify with leads.

**Comment by romatitan** [comment]
Not yet fix

**Comment by Santosh-titan** [comment]
![hover img](https://cloud.githubusercontent.com/assets/13828562/10277992/91af50cc-6b77-11e5-86bc-fbed0a5254fa.png)
please see the attached screenshot for every alternate leadin was hovered with  #d71921 and #c10013 respectively
