### ISSUE TITLE
Clarification: "Have questions" button's function is to link to the FAQ page with that, I guess it should not be included in the FAQ sidebar.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Modern-Education-Student-Exchange-Services#63]
![image](https://cloud.githubusercontent.com/assets/12888048/9625707/b2d1e424-518a-11e5-98aa-fdf84867f2ca.png)

**Comment by Santosh-titan** [comment]
I just implemented as in design.

**Comment by romatitan** [comment]
Kindly remove the "Have questions" button in the FAQ page sidebar.
