### ISSUE TITLE
Clarification: What will be the use of the "Useful Links" page?

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Modern-Education-Student-Exchange-Services#76]
![image](https://cloud.githubusercontent.com/assets/12888048/9624603/0c12c3dc-5181-11e5-9af8-f09ae00936b1.png)

**Comment by Santosh-titan** [comment]
No use of  "Useful link" page. So i moved this page into trash

**Comment by romatitan** [comment]
Kindly remove the "Useful Links' page.
![image](https://cloud.githubusercontent.com/assets/12888048/9841953/ff3baf7c-5ad9-11e5-80b9-d47d2c163267.png)
![image](https://cloud.githubusercontent.com/assets/12888048/9841954/00ea6ef8-5ada-11e5-86b3-4a0013490ad7.png)
