### ISSUE TITLE
Clarification - Visa leads:  If the visa lead-ins to be displayed on the page were 6 items only, how about the other visa lead-ins (custom post) created aside from the 6? Should a visa leads custom post has a featured ACF, so the user can choose which items they wish to be featured or display on the page?

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Modern-Education-Student-Exchange-Services#8]
Are we going to limit the visa lead-ins to be displayed up to 6 items only?

**Comment by Santosh-titan** [comment]
ACF Checkbox created for leadins.

**Comment by romatitan** [comment]
Are we going to limit the visa lead-ins to be displayed up to 6 items only?
What if the client wants to featured more than 6 lead-ins?
What is set to be featured (regardless of how many items) should be displayed in the frontend?

**Comment by romatitan** [comment]
Are we going to limit the visa lead-ins to be displayed up to 6 items only?
What if the client wants to featured more than 6 lead-ins?
What is set to be featured (regardless of how many items) should be displayed in the frontend?

**Comment by Santosh-titan** [comment]
You can display more than 6 images but you need to check as featured lead-in to display on home page.
