### ISSUE TITLE
General - Header: Missing Chinese translation button.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Modern-Education-Student-Exchange-Services#98]
Affected page(s):
Thank You page
News Single page
Study in Australia single page
Study in China single page

![image](https://cloud.githubusercontent.com/assets/12888048/9868682/7f3b705c-5bae-11e5-9ddf-7fb20a83ec49.png)
![image](https://cloud.githubusercontent.com/assets/12888048/9868683/807434e0-5bae-11e5-8867-3f9a3034a6ee.png)
![image](https://cloud.githubusercontent.com/assets/12888048/9868684/854cf7d6-5bae-11e5-8c45-c5c5f584cd0d.png)
![image](https://cloud.githubusercontent.com/assets/12888048/9868686/8a59207e-5bae-11e5-975c-3df170aaed5b.png)

**Comment by Santosh-titan** [comment]
It don't show chinese translation button if the page/post is not  created for chinese language. As of now we don't have web copy thats why I didn't added posts(All custom posts) for chinese language.

**Comment by romatitan** [comment]
Can you please confirm it with the pm of this project.

Thanks.

**Comment by romatitan** [comment]
@Santosh-titan 

Regarding the translation button(chinese) for the custom post, can you please confirm this to the project's PM.

![image](https://cloud.githubusercontent.com/assets/12888048/10328554/b623e2fc-6ce8-11e5-87a3-bc12794f784c.png)

**Comment by Santosh-titan** [comment]
I sent a mail  to PM regarding this issues. I will get back to you once I get response.

**Comment by romatitan** [comment]
Note: Pending issue

**Comment by Santosh-titan** [comment]
Hi @romatitan
I got response form PM regarding this issue.
"Client will provide the Chinese version, as long as the button shows when the added content is on the backend of the website to translate "
